### ISSUE TITLE
Error on Minigo v15(990)

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#10]
The Minigo v15(990) that came with the megapack a little while ago, I get an error when I try to start it with sabaki.
The GTP console on the left will show "Could not open weights file: weights/minigo_v15-990.gz".
In the case of lizzie, it shows 13 roads and it doesn't seem to do the search correctly.
If anyone knows anything about this, please advise.

**Comment by wonsiks** [comment]
I've removed MiniGo v15 from prior version of Megapack because of heavy file size.
I think I didn't remove it's engine setting from Sabaki.
If you want to use MiniGo v15 then you need to search and download the net file.

**Comment by hope366** [comment]
The current version of the megapack doesn't come with V15, but I'm using a slightly earlier megapack and it comes with v15.
When I try to make that v15 work with sabaki, I get an error.
The V16 and V17 work fine.
Do I need a new download? However, I currently have a V16 on hand.

**Comment by hope366** [comment]
Thank you very much for your quick response.

The current version of the megapack doesn't come with V15, but I'm using a slightly earlier megapack and it comes with v15.
When I try to make that v15 work with sabaki, I get an error.
The V16 and V17 work fine.
Do I need a new download? However, I currently have a V16 on hand.

**Comment by wonsiks** [comment]
If you want to use v15 even though it's not latest version here is download link for you.
[https://drive.google.com/open?id=1qDUwdZu0kCzmT21vhui4uFVAlxKyvjG8](https://drive.google.com/open?id=1qDUwdZu0kCzmT21vhui4uFVAlxKyvjG8)

**Comment by hope366** [comment]
I downloaded v15 from google drive and it worked fine with sabaki.
I thought it wouldn't work because the file name and size were exactly the same as the existing v15, but it was unexpected.
Does this mean that any improvements have been made?

Thank you very much.

**Comment by wonsiks** [comment]
I'm not sure about the reason why it didn't work.
However there's no further improvement in Minigo v15 weight file.
I guess it has just came from file w/r failure or something.

**Comment by hope366** [comment]
I want to know the detailed reason which did not move, but I am satisfied that I was able to start normally with sabaki for the time being.

Thank you very much for your kind response.
