### ISSUE TITLE
KataGO Config not working

### ISSUE THREAD

**Issue by AlingoAlingo** [wonsiks/BadukMegapack#12]
Generate KataGo Config not working !
![IMG_20200512_084442](https://user-images.githubusercontent.com/33194033/81644597-b557e980-9430-11ea-9db6-5b882fcfb940.jpg)

**Comment by AlingoAlingo** [comment]
Only this version gives this error: Baduk_AI_Megapack_v4.1_x64

**Comment by wonsiks** [comment]
Oh, I've recognized that genkatacfg.bat file has a typo so error occurs.
I've repacked the installer file and uploaded.
You can download again then there're no problem.
Sorry for your inconvenience.

**Comment by AlingoAlingo** [comment]
Thank you

**Comment by AlingoAlingo** [comment]
I downloaded the installer again and the problem persists !

**Comment by AlingoAlingo** [comment]
Please test before release !

**Comment by AlingoAlingo** [comment]
> Oh, I've recognized that genkatacfg.bat file has a typo so error occurs.
> I've repacked the installer file and uploaded.
> You can download again then there will be no problem.(filename is same)
> Sorry for your inconvenience.
I downloaded the installer again and the problem persists !
Please test before release !

**Comment by AlingoAlingo** [comment]
I downloaded the installer again and the problem persists !
Please test before release !

**Comment by wonsiks** [comment]
@AlingoAlingo I've just fixed the error and uploaded.
It caused from typo in neuralnet files.
Sorry again about the inconvenience.
I've tested this time.
Good luck.

**Comment by AlingoAlingo** [comment]
o.k thanks

**Comment by AlingoAlingo** [comment]
Yes, it works well now.
Thank you
