### ISSUE TITLE
Globis-AQZ stop

### ISSUE THREAD

**Issue by AlingoAlingo** [wonsiks/BadukMegapack#14]
Hallo!
I found another problem
Globis-AQZ stops from analyzing after 32,000 playouts in Lizzie for no reason

**Comment by wonsiks** [comment]
AQZ limits playout because of memory usage issue.
If your hardware good enough you can make it larger.
Open config.txt file in AQZ folder, then change --node_size=32768 into bigger number you want.

**Comment by AlingoAlingo** [comment]
o.k thanks

**Comment by AlingoAlingo** [comment]
Please do you this before release.
Put a much larger number.
Thanks
