### ISSUE TITLE
About Zen7

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#18]
Is "ZEN7" registered in sabaki the "Zenith Go 7 ZEN" sold in Japan?
Has this been published anywhere?

When running Zen7 with sabaki, the CPU usage is very high and the GPU does not appear to be running. Is there a way to reduce the CPU usage and run the GPU instead?
Also, the Zen7 always uses 5 seconds of consideration time, is there any way to adjust this?

**Comment by wonsiks** [comment]
The sabaki settings will not work unless Zen.dll file is in lizzie folder.
This means it's for users who have Zenith Go 7 program for their convenience.
If you want to play against Zen 7 through Sabake, you have to put Zen.dll into lizzie folder.

**Comment by hope366** [comment]
Zen.dll has been downloaded because I needed it to use lizzie's "form factor".
This is the first time I've learned that it's also necessary when playing against each other in SABAKI.

Thank you very much.

**Comment by AlingoAlingo** [comment]
Where did you download zen.dll?

**Comment by hope366** [comment]
https://github.com/featurecat/lizzie/commit/d8ab2a158c2d6bb04b5752ae4e31041669bbb685
Click on "..." on the right side of "BIN +46.2 MB Zen.dll" on this page to open a pull-down menu. Click "View File" in the menu. Then you can download it if you click this because there is "Download" on the right.

**Comment by AlingoAlingo** [comment]
What rule of play does zen use?
Chinese or Japanese
it is possible to change
End Thank you for zen.dll

**Comment by wonsiks** [comment]
@AlingoAlingo Zen program itself is a product of Japanese company and doesn't support Chinese rule.

**Comment by AlingoAlingo** [comment]
O.k thank you

**Comment by hope366** [comment]
Since the discussion seems to be over once and for all, I will close this issue.
