### ISSUE TITLE
About pachi

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#24]
Hello.
Here's a question about Pachi.
When I download the latest version of pachi-12.50 and try to run it with sabaki, I get a message from the antivirus software that there is something wrong with pachi.exe. If you ignore the message and run it, it works, but it's kind of creepy.

The megapack pachi works fine without any errors. Megapack has pachi_19x19.exe in addition to pachi.exe, and this is specified in sabaki.
I think this is why there are no errors.

So you found something wrong with pachi.exe and wonsiks prepared pachi_19x19.exe instead of this one?

**Comment by wonsiks** [comment]
I've downloaded new pachi from https://github.com/pasky/pachi and you can find more about pachi there.

**Comment by hope366** [comment]
Thank you very much.
I will read the page you referred me to closely.
