### ISSUE TITLE
About setting up KataGo

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#28]
Thank you for using the Mega Pack.
Let me ask you one question.

With KataGo setup,
”KataGo will cache up to about 3GB of positions in memory (RAM), in addition to whatever the current search is using. Specify a max in GB or leave blank for default''
What is the difference when you specify "3" here compared to the default?
When I started KataGo with lizzie, I couldn't see the difference when I looked at the memory usage of Task Manager.
The cfg file did not seem to be rewritten.

Sorry for my poor English

**Comment by wpstmxhs** [comment]
KataGoのメッセージは空白のままに置けば基本的に３ギガバイトのメモリーまで使うという話です。
だからこの欄に「３」と書けば基本設定と一緒なので変わりがないのは自然です。
もっと多いメモリーを使いたければ「３」より高い数字を入れてください。

**Comment by hope366** [comment]
回答有難うございます。
なるほどそういうことでしたか。
しかし「５」を指定してみたのですが、どこに変化が現れているのかがよく分かりませんでした。

Thank you for your response.
I wonder if that was the case.
However, I tried to specify "5", but I was not sure where the change was.
