### ISSUE TITLE
Cancel updating lz weights before opening lizzie

### ISSUE THREAD

**Issue by Dreamkeeper66666** [wonsiks/BadukMegapack#3]
Thanks for your installer! It's really helpful. I think it's better if we can cancel the update check before opening lizzie. Is it possible to modify? Thanks!

**Comment by wonsiks** [comment]
You can edit Lizzie.bat from C:\baduk\lizzie folder.
Write as below at line 4,
goto passing
Then lizzie will never check update.

**Comment by Dreamkeeper66666** [comment]
> You can edit Lizzie.bat from C:\baduk\lizzie folder.
> Write as below at line 4,
> goto passing
> Then lizzie will never check update.

Thanks for your reply! It works. By the way, can I change the theme back to lizzie's?  Since it's sabaki's theme now.

**Comment by wonsiks** [comment]
@Dreamkeeper66666 You can edit config.txt from C:\baduk\lizzie folder.
Find "theme": "sabaki" and change to "theme": "default"

**Comment by wonsiks** [comment]
@Dreamkeeper66666 There's no language option as I know.
However, Lizzie seems to detect some languages. It shows some Korean messages on my computer.
