### ISSUE TITLE
Megapack v.4.7.4 CPU Lizzie colab-katago

### ISSUE THREAD

**Issue by tedthegypsy** [wonsiks/BadukMegapack#31]
Seventeen -san
I'm a user of Katago of Megapack.
Thank you very much.
I have installed Megapack v4.7.4.
I opened Lizzie , then I noticed that there is colab-katago.exe in engine 2.
When I start engine 2, colab-katago will start working immediately.

There are a few things I'd like to Know.
① You no longer need to connect to Google Drive to use colab-katago as before, right?
② Is this only for CPU users?(Suprise for CPU users?)
③ Do you need at least a Google account?
④ There is no commentary for this change.
   Do you have any plans to explain?

**Comment by wonsiks** [comment]
Megapack is just including colab-katago.exe file.
You must have google account and run colaboratory.
If you can connect without anything then it would be connected to someone's colab because I've made colab notebook image for people who're using megapack and the id and passwords are same(not changed).
You can check my colab image here.(applied japanese rule and 6.5 komi)
https://colab.research.google.com/drive/1Nn2hmmDj7Az7MRHuLHoD8F8ZbkcnjNSM?usp=sharing

And you may look into kinfkong's github too.
https://github.com/kinfkong/katago-colab

**Comment by tedthegypsy** [comment]
Thank you for your answer.

Now I understand  when Ｉrun Engine2 (colab-katago. exe), it is connected to 
someone's colab (the one you set up for everyone's use).
Although I don't understand the mechanism of connecting to
 your colab automatically, it's very convenient because you don't have to 
connect to your own Google Drive  before running colab-katago. exe.

It doesn't seem  GPU users get any of this kind in their Engine
in Megapack v4.7.4.
I wonder if they rewrite one of their engines to 
 /colab-katago.exe katago 20b, will it work? 
on the condition they have a Google account ,of course.

Hope I'm not misunderstanding the meaning of your answer.

**Comment by wonsiks** [comment]
@tedthegypsy Actually I've released another installer beside megapack.
It's written in Korean but you can check what it is if you want.
http://naver.me/58hVIZEz

**Comment by wonsiks** [comment]
@tedthegypsy Oh, you have to copy my(or kinfkong's) colab notebook image to your own google drive then get ngrok_token and put it into the launch script and run it.
You may change id and password from the launch script and from lizzie engine setting too.

**Comment by tedthegypsy** [comment]
Thank you for your information.

Only lizzie and colab-katago.(no other engines)  seems great,
because I only use KataGo in Megapack.
Will check it out.

Going back to Engine2(Your colab), this must be sharing service  of Google Drive, right?
so,anyone could connect to it without having their own Google Colabatory.

**Comment by wonsiks** [comment]
@tedthegypsy No, it's not. You must run your own colab before connect to it.

**Comment by tedthegypsy** [comment]
And yet it moves(Galileo) LOL
you've lost me.

I have my own colab-katago in Google Drive(NGROK_TOKEN、USER_NAME、USER_PASSWORD, as well)
Without connecting to Google Drive, as I clic Engine2 , Katago starts working.

I saw those who say the same in a Bulletin board.
Will you wait a little.
Let me ask him how he operates, and I'll get back to you.

**Comment by wonsiks** [comment]
I'm not sure but I guess with same id and password colab-katago probably connect to any running colab which has same id and password in spite of different token value.
When you connect engine2 from megapack then possibly it would work or not by there's someone who is running google colab with same id and password(katago, 20b).

**Comment by tedthegypsy** [comment]
hahaha 😅

My silly  misunderstanding!
The facts  you think is that only when someone is running colab-katago with any token value but  with same id and password(katago, 20b),  then I can connect colab-katago with only clicking Engine 2.
It seems  so.

**Comment by wonsiks** [comment]
@tedthegypsy Yes, that's what I've meant. haha

**Comment by tedthegypsy** [comment]
I finally got it off my chest!
Thank you.

**Comment by wonsiks** [comment]
@tedthegypsy Sorry about my poor English.

**Comment by tedthegypsy** [comment]
No,No, Don't mention that.
My english _**is**_ terrible.

Almost every day I use KataGo in Megapack.
Thank you.
And thank you for answering my first  and silly  question.

I'm a cheap CPU user in Japan.
Perhaps I  ask a silly question or two, again .
Kamsahabnida
