### ISSUE TITLE
Can you verify the jar file that will be released as Lizzie-improved-v2.2?

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#35]
https://drive.google.com/file/d/1N6-vQz9mSMQ2rFgUshb8hqE284jJ3c91/view?usp=sharing
This is a jar file that will be released as Lizzie-improved-v2.2.
The following functions have been added to the "Region of interest".

 * In v2.1, all the change diagrams presented were also limited to the specified area, but in v2.2 the entire board is used.
 * In v2.1 it was limited to normal mode, but in v2.2 it can also be used in panel UI mode.
 * In v2.1, if you release Alt before the mouse button, the area specification will fail, but in v2.2 it will be valid.
 * You can now cancel the set analysis area by clicking "Allow" or "Avoid" in the right-click menu. (Only when the engine is Leela Zero and Settings-> Engine-> Avoid Keep Variations is other than 0)
 
Could you please verify whether you can still switch between enlargement and reduction of the winning percentage graph?
It seems that the code for the third function above and the code for solving the problem of enlargement ⇔ reduction of the winning percentage graph are in conflict.
If the above jar file still seems to have problems with the winning percentage graph, we will cut the third feature (not a significant feature).

By the way, the following functions have been added to v2.2.
* Score calculation function: In Game → Score game, if you click the dead stone, the score will be displayed in the Agehama display.
* "Help" has been added to the right edge of the top toolbar. It is a link to a page that explains how to use the keyboard in detail.
* You can select various rules from Analysis → Rule. (KataGo only)
* Lizzie was unresponsive when auto-analyzing at the end of the game, but now displays an error message.

I'm sorry, I should have written in Lizzie-improvements. I tried to move it, but I couldn't delete it ...

**Comment by wonsiks** [comment]
I've just tested v2.2 and all working fine.
Thank you for your work.

**Comment by hope366** [comment]
Thank you for your verification.
Lizzie-improved-v2.2 will be released in line with the release of KataGo-v1.8.0.
