### ISSUE TITLE
How can I get the previous versions of Megapack with Globis-AQZ v4.0.0?

### ISSUE THREAD

**Issue by SHKD13** [wonsiks/BadukMegapack#37]
Hi!
I cannot find where to download the previous versions of Megapack. Could someone gimme a link?
I'd like to run Globis-AQZ with BadukMegapack, but the newest 4.8.7 version of GUI does not contain AQZ v4.0.0. Where can I get the GUI version with AQZ? 

The reason I need BadukMegapack with AQZ is I can't manage to run AQZ directly via Lizzie or Sabaki with my RTX 3060 Ti and appropriate newest CUDA, cuDNN and TensorRT software. With all routine automated in BadukMegapack it seems much easier to run AQZ with.

**Comment by wonsiks** [comment]
https://drive.google.com/file/d/1XjrAJ4fYvookfKHSQi0BcR-PsgiEZXK2/view?usp=sharing
