### ISSUE TITLE
Something wrong：Uncaught exception

### ISSUE THREAD

**Issue by wuchangmin** [wonsiks/BadukMegapack#39]
for Lizzie and Sabaki：Uncaught exception: Key 'startupPrintMessageToStderr' + was specified multiple times in C:\baduk\lizzie/default_gtp.cfg, you probably didn't mean to do this, please delete one of them
for  Katrain：status 3221225477
The version：v4.9.7

**Comment by wonsiks** [comment]
1) I'll fix this on next release.
2) You can manually fix default_gtp.cfg file.
Thank you for reporting this bug.
