### ISSUE TITLE
Somebody wrote “random install files from unknown sources” and now I’m confused

### ISSUE THREAD

**Issue by Spoekenkieker** [wonsiks/BadukMegapack#4]
I shared the link to [BadukMegapack](https://github.com/wonsiks/BadukMegapack) in a large Go group on Facebook, and somebody wrote [this comment](https://www.facebook.com/groups/go.igo.weiqi.baduk/permalink/10157757632601514/?comment_id=10157758876891514):
> Obvious disclaimers about just downloading random install files from unknown sources off the internet. Especially when they use the reputation of github simply to host the instructions and actually host the closed installer in a google drive.

I know close to nothing of coding, and I also don’t know how to check what the installer actually installs … can anybody tell me whether it’s possible to ensure that this installer doesn’t install any malware/spyware/adware, and how?

**Comment by wonsiks** [comment]
@Spoekenkieker I don't know how to do with ensuring my installer file safe by registeing which organization or something.
Anyway I've just made easy installer for people.
If somebody can't trust this, just ignore this then everything would be fine.
Actually more than 10 thousands people visit my blog and using my installer in Korea.

**Comment by Spoekenkieker** [comment]
Thanks for your reply, @wonsiks, I (think I) understand :-)
