### ISSUE TITLE
There is no "generate katago config" process.

### ISSUE THREAD

**Issue by hebaeba** [wonsiks/BadukMegapack#40]
I always use megapack with great appreciation.
I installed v4.10.3 and noticed that the "generate katago config" process was gone. This makes the installation go much faster.
Does this process apply to future megapacks?

**Comment by wonsiks** [comment]
@hebaeba I've got rid of leelazero tuning process when install.
But katago config generation is still in the setup process.

**Comment by hebaeba** [comment]
Oh my, I see.
I am a windows user in Japan.
When I install it, I get the message "The specified file is missing" as shown in the image, then the screen disappears. Then when I start the installed megapack of Lizgoban, I get the error "A JavaScript error in the main process". The rest of the AI seems to be installed fine.
It seems to be terminating before the "generate katago config" process.
Is this only happening to me?
![megapack](https://user-images.githubusercontent.com/57716061/124549747-91dcd300-de6a-11eb-8a00-3889b58c3fea.jpg)

**Comment by wonsiks** [comment]
@hebaeba It's strange.
Have this problem happened before?

**Comment by hebaeba** [comment]
I am using an RTX2080.
I was able to set up Megapack up to v4.10.1 fine, I haven't tried 4.10.2, but this started happening with 4.10.3. I just tried 4.10.4 and it was the same.
In addition, I don't know when it started, but the English menu "Generate a new KataGo config file" stopped appearing before. Does this have anything to do with it?
![megapack2-2](https://user-images.githubusercontent.com/57716061/124564267-db81e980-de7b-11eb-8b31-d23823cbd395.jpg)

**Comment by hebaeba** [comment]
During the installation process, the black screen disappears, but the installation process seems to be running internally. However, there is nothing on the screen, so no further processing is possible.

**Comment by wonsiks** [comment]
@hebaeba Oh, I've just found out the bug.
Just have fixed it and re-uploading.
Please download installer again when it is ready.
Sorry about letting you in trouble.

**Comment by hebaeba** [comment]
@wonsiks  The new version was set up correctly and all the software is working properly.
Thank you very much for your quick response.
