### ISSUE TITLE
Questions and suggestions

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#41]
Hello, seventeen.
After installing the GPU version of megapack, I placed katago-eigen in the lizzie folder. Then I registered katago-eigen to the lizzie engine and tried to run it.
I found that the startup time and the analysis speed were much faster with the megapack than with lizzie and katago separately.
I think that the following three files are related to the analysis speed, is this correct?
* boost_filesystem-vc141-mt-x64-1_70.dll
* boost_system-vc141-mt-x64-1_70
* Qt5Core.dll

I don't know which file is affecting the speed from startup to the start of the analysis. Please let me know if you don't mind. 

Next, I have one suggestion.
Today's mega packs are great on their own, but why not get a slim pack just for Lizzie and KataGo?
This is because many Japanese Go fans are elderly, and most of the PCs they use have low CPU performance.
The current 2.2GB can take a couple of hours to download and install, but KataGo and Lizzie alone can save you a lot of time.
We would appreciate it if you could consider it.

**Comment by wonsiks** [comment]
I have no idea of which files are concerned to analysis speed.
KataGo engine files are all came from original release, so those files you listed are must came from other program.

People who uses old PC can try light version of megapack.
It's size is under 200mb and contains lizzie and katago and some other tools.

**Comment by hope366** [comment]
Thank you for your answer.
Anyway, it's interesting that using Megapack is faster than running katago alone.

I completely forgot about the light version of the megapack.
I'm sorry for making a noise.
