### ISSUE TITLE
Some questions about the latest release 

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#44]
Hello, thank you for your hard work. 
I have some questions about this release, so I would like to ask you a question. 

The Baduk AI Softwares folder is missing from this release, is this intentional? In Megapack, LizGoban can only be started from this folder, and if you try to start it from a normal LizGoban folder, you will get an error. In other words, LizGoban cannot be started with this mega pack. 

Next, the bottom part of default_gtp.cfg is as follows. 

>startupPrintMessageToStderr = true
ogsChatToStderr = true
defaultBoardSize = 19
startupPrintMessageToStderr = true
ogsChatToStderr = true
defaultBoardSize = 19

This is why I got an error when starting lizzie. I deleted the bottom three lines and it started normally, but is there any special meaning to repeating the same description? 

Next, regarding Sabaki, v0.52.0 has been removed. I personally like v0.43.3, but some people seem to be disappointed with the lack of v0.52.0. Please let me know why you deleted v0.52.0. 

Lastly, regarding lizzie-improved-v3.0, the one included in the megapack has a slightly different file size compared to the one I released. I would like to know exactly what is different and how, can you answer? 

Thank you for your cooperation.

**Comment by wonsiks** [comment]
@hope366 Thank you for your report.

1) People usually delete "Baduk AI Softwares" folder from desktop and leave some mostly using app's icons so I've removed that folder. You can run any programs from "Baduk AI Software" in stat menu.
2) I've not recognized those three lines are repeated twice. I'll check it and fix.
3) I thought LizzieYZY can cover Sabaki's roles especially AI vs. AI play so I've removed Sabaki 0.52.0 to save some disk space(actually it's not big though). I'll put it again in next version if you and other users want.
4) I've recompile from your code to change Korean language file for Korean users.

Have a good day.

**Comment by hope366** [comment]
Thank you for your prompt response. 
Regarding "Baduk AI Softwares", it was possible to start from the start menu even in the previous version. I forgot to check it this time. 😅 By starting from the start menu, LizGoban was able to start normally. 

Actually, it's a trivial matter, but it was brought up in a forum I usually use, so please allow me to ask a question. In your description of TensorRT-related releases, you write that the RTX 20 series is... and you seem to have intentionally excluded the RTX 30 series, and I would like to know why.

**Comment by wonsiks** [comment]
@hope366 I've changed the description to RTX 20 series or above.
Thanks for the information. :)

**Comment by hope366** [comment]
I'm sorry, I was able to boot from the start menu, so it seems that the previous version of Megapack was saved in the D drive. After removing this, Baduk AI Softwares disappeared from the Start menu.
Is it a "stat menu" instead of a "start menu"? Where is it? 
>I've changed the description to RTX 20 series or above.

Thank you for your support.

**Comment by wonsiks** [comment]
@hope366 And I couldn't find out why the last three lines are repeated in your case.
I've tested it myself and there wasn't any problem.

"stat menu" was a typo...

**Comment by hope366** [comment]
>I've tested it myself and there wasn't any problem.

Just in case, I'll remove everything and try installing Megapack again.

**Comment by hope366** [comment]
After reinstalling, there was a display of Baduk AI Softwares in the start menu 😄
Also, the last three lines of default_gtp.cfg were not repeated. Maybe it was because I had the previous version saved on the D drive.
Thanks to your support, the problem seems to have been resolved. thank you very much.
