### ISSUE TITLE
A cache file is created when performing a flash analyze 

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#46]
If you set the Tensor RT version of KataGo to the engine with Lizzieyzy of the mega pack, it will take some time because the cache file is created at the first startup.
Then, after this cache file is created, try performing a flash analyze. Then it will take some time to create the cache file for flash analysis.
This means that you need separate cache files for regular analysis and flash analysis.

When I download and run Lizzieyzy independently, the cache file is created only for the first time, and a new cache file is not created at the time of flash analysis. What is the reason for this difference?

**Comment by wonsiks** [comment]
@hope366 Cache files are created for each blocks of neuralnets. And I guess you can configure both neuralnets for normal analysis and flash analysis as same blocks then there're no more cache file creation.

**Comment by hope366** [comment]
> And I guess you can configure both neuralnets for normal analysis and flash analysis as same blocks 

I don't really understand what this means.
For example, suppose you have only a 40 block neural network here.
Lizzieyzy of Megapack creates a cache file for nomal analysis and a cache file for flash analysis separately.
Stand alone Lizzieyzy creates a cache file for nomal analysis, but for flash analysis it appears to be running with that cache file (it doesn't create duplicate cache files like a megapack.

**Comment by wonsiks** [comment]
@hope366 Lizzieyzy in megapack uses 6 blocks neuralnet for flash analysis.
If you mainly use 40 blocks neuralnet when cache file for 40 blocks has been made but not for 6 blocks.
So if you change neuralnet for flash analysis into 40 blocks then there's no more cache will be built I guess.
<img width="445" alt="20211126_215633" src="https://user-images.githubusercontent.com/37356450/143585096-77af5d39-ee2a-45d4-a54d-cae13bb7e14e.png">

**Comment by hope366** [comment]
I did a 6-block normal analysis, a 6-block flash analysis, a 40-block normal analysis, and a 40-block flash analysis on the Megapack Lizzieyzy. Separate cache files have been created for each. 
![無題](https://user-images.githubusercontent.com/63999713/143587428-be82c8b9-fe44-4a14-8cf0-405aa58d1c27.png)

In a stand alone Lizzieyzy, 40 blocks of normal analysis, 40 blocks of flash analysis, and 60 blocks of normal analysis were performed, but two cache files were created. In other words, during the 40-block flash analysis, the 40-block cache file for normal analysis was used, so no new cache file was created. 
As you can see, there is a difference between the standalone Lizzieyzy and the megapack Lizzieyzy. 
![無題1](https://user-images.githubusercontent.com/63999713/143588130-3cb7fe47-3b50-471a-bb4a-ee4f89654080.png)

**Comment by wonsiks** [comment]
@hope366 Can I see full names of cache files?

**Comment by hope366** [comment]
The bottom four are the megapack cache files. 
g170-b6c96-s175395328-d26788732_gpu_75_19x19_batch96_fp16
g170-b6c96-s175395328-d26788732_gpu_75_19x19-exact_batch24_fp16
kata1-b40c256-s10336005120-d2519775087_gpu_75_19x19_batch96_fp16
kata1-b40c256-s10336005120-d2519775087_gpu_75_19x19-exact_batch24_fp16

The bottom two are standalone Lizzieyzy cache files. 
kata1-b40c256-s10382453504-d2531003754_gpu_75_19x19-exact_batch16_fp16
kata1-b60c320-s4577723904-d2458479936_gpu_75_19x19-exact_batch24_fp16

**Comment by wonsiks** [comment]
@hope366 I'm not sure what parameters in configs of default_gtp.cfg and default_analysis.cfg make that difference.
I even don't have GPU to test TensorRT actually.

**Comment by hope366** [comment]
I know that changing the value of "numSearchThreads" will generate another new cache file, but this is about default_gtp.cfg.

Regarding analysis_example.cfg, I feel that the following three are related, but I'm still not sure. I would like to continue to investigate. 
numAnalysisThreads = 2
numSearchThreadsPerAnalysisThread = 16
nnMaxBatchSize = 64

**Comment by hope366** [comment]
Lizzieyzy also required separate cache files for regular and flash analysis.
Probably my misunderstanding. We're sorry for the inconvenience.
By the way, interesting information on this issue can be found on the Issues of Lizzieyzy. 
https://github.com/yzyray/lizzieyzy/issues/46
