### ISSUE TITLE
The engine is not registered

### ISSUE THREAD

**Issue by hope366** [wonsiks/BadukMegapack#48]
hello.
I haven't updated the megapack recently, but today I installed the latest "v4.14.0".
I noticed something strange there.
Previously, many engines were already set up when you started lizzie or Sabaki. However, the engine of this mega pack is not registered at all.
For example, with lizzie, only "lznetwork.gz" (lizzie's default) is available.
Since the file lznetwork.gz is not included, the error shown in the attached figure will occur.
Sabaki and Lizzieyzy are all empty as well.
Do you have any good advice on how to solve the problem?
thank you.

![無題](https://user-images.githubusercontent.com/63999713/171380149-a999c663-d356-4087-a9d8-c3ab91c90152.png)

**Comment by hope366** [comment]
Thank you for your quick response.
I asked some people other than me to check it, but they all seemed to have no problem.
I would like to continue to investigate where the problem is.

**Comment by hope366** [comment]
Last time I used Google Drive, but this time I used Mega Cloud.
But unfortunately the result was the same.
For reference, I uploaded the "config.txt" file in the lizzie folder of the megapack. It does not seem that various engines are registered.
https://drive.google.com/file/d/1mMeIoSmxojGckCR4CZmW1nHNo3FPW3kW/view?usp=sharing

**Comment by hope366** [comment]
With the previous Mega Pack, I was asked what kind of GPU is installed in my computer during the installation.
However, for the latest version of the Megapack, I wasn't asked what kind of GPU it was.
Is the latest megapack designed that way?

**Comment by hope366** [comment]
When you run the installer, you will first see a window like the one below.

![無題](https://user-images.githubusercontent.com/63999713/171542465-3e1a37a7-24f4-4391-8ca7-9205d7c73cbd.png)
If you click "Install", you will see the following display for a very short time (about 0.5 seconds).

![無題1](https://user-images.githubusercontent.com/63999713/171542641-e5e66242-d53c-43c8-8e94-c974206e8fb7.png)
The displayed Japanese is as follows.
* 'xcopy' is not recognized as an internal or external command, operable program or batch file.
* The specified file could not be found.
* 'powershell' is not recognized as an internal or external command, operable program or batch file.
* I copied one file.

Immediately after this display disappears, the following display will be displayed.
![無題2](https://user-images.githubusercontent.com/63999713/171543527-3f45bf71-4b7e-48a3-90a9-110e69cd06be.png)

There doesn't seem to be a step to ask what kind of GPU it is.
It would be nice if the information I provided had a clue to solve the problem ...

**Comment by wonsiks** [comment]
@hope366 Your case seems that your path setting in environment variables is damaged so that the %path% doesn't contain basic folders such as C:\Windows\System32 and C:\Windows\System32\WindowsPowerShell\v1.0

**Comment by hope366** [comment]
With your advice, I've added the following two to the user environment variables:
* C:\Windows\System32
* C:\Windows\System32\WindowsPowerShell

Then a change happened. First, when I ran the Megapack uninstaller, something was only displayed for a moment until now, but this time a window has popped up asking if I want to uninstall it.
Also, there is a display to determine the GPU type that is displayed during the installation.
config.txt exists in the lizzie folder and is working fine.

However, Lizzie Yzy is still unknown. There is a config.txt that suggests that various types of engines are registered, but it changes to "config_wrong.txt" immediately after startup, and a new blank config.txt is generated. Does this still mean something is wrong?
Similarly, Sabaki has no engine registered.

I've played with environment variables in Java before. This may be the cause.

**Comment by hope366** [comment]
The items currently registered in the user environment variable "Path" are displayed below.

![無題1](https://user-images.githubusercontent.com/63999713/171558763-bf14788a-e181-4a6a-9591-e87c49a5dd16.png)

Similarly, it is an item registered in the system environment variable "Path".

![無題2](https://user-images.githubusercontent.com/63999713/171558871-9a6bf135-8f78-4ba3-9074-a5059ff5a311.png)

**Comment by hope366** [comment]
There was the following description as the default value of the system environment variable "Path" on the net, so I applied it to my personal computer.

%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\

After erasing the existing megapack and then reinstalling the new megapack, Lizzie, LizzieYzy, Sabaki, LizGoban, KaTrain, all worked fine.
Thanks to your advice on environment variables. Thank you very much.
