### ISSUE TITLE
Komi is not reflected correctly

### ISSUE THREAD

**Issue by hebaeba** [wonsiks/BadukMegapack#5]
Firstly, thanks for your wonderful works.
When using katago with the latest megapack, reading sgf files does not correctly reflect the Komi.
If I change the komi after startup, it will be correct komi, but it is inconvenient.

**Comment by wonsiks** [comment]
@hebaeba Please check your sgf file with any text editor.
Because some sites use wrong tag for komi.
Proper komi tag is [KM].

**Comment by hebaeba** [comment]
Thanks for the quick reply.
As you say, the sgf file was KM (0). It seems that the correct komi was not saved when saving the file.
so I'm closing this issue.
