### ISSUE TITLE
Missing -override-config in config.json of LizGoban for KataGo

### ISSUE THREAD

**Issue by kaorahi** [wonsiks/BadukMegapack#7]
I've heard that config.json of LizGoban lacks `-override-config` for KataGo in BadukMegapack. This can cause two problems.

(1) Initializations of 9x9 and 13x13 are twice as slow as that of 19x19.

(2) KataGo does not play aggressively in handicap games.

For (1), would you consider modifying KataGo parts in config.json like this? ("=19" is ok. It is replaced with 9 or 13 inside LizGoban automatically.)

~~~~
"engine": ["C:/baduk/lizzie/katago", "gtp","-override-config","defaultBoardSize=19","-model","C:/baduk/lizzie/KataGo20b.bin.gz"]
~~~~

For (2), how about adding something like this into config.json? It is necessary for high handicap games because LizGoban cannot use KataGo's dynamical adjusting of aggressiveness at present.

~~~~
{
    "label": "KataGo 40b (handicap)",
    "engine": ["C:/baduk/lizzie/katago", "gtp","-override-config","defaultBoardSize=19, dynamicPlayoutDoublingAdvantageCapPerOppLead=0.00, playoutDoublingAdvantage=2.00","-model","C:/baduk/lizzie/KataGo40b.bin.gz"]
},
~~~~

See https://github.com/kaorahi/lizgoban/blob/v0.4.0-pre3/README.md for details.

**Comment by wonsiks** [comment]
Thank you for inform me.
I've just fixed it and finishied uploading.
Have good day~

**Comment by kaorahi** [comment]
thx for your quick response, every time!
